version: '3'

services:
  php:
    build:
      context: .
    volumes:
      - ./:/var/www/html
    ports:
      - "9010:9000"

  web:
    image: nginx:1.17
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - .docker/nginx/nginx_template_local.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "90:80"

  db:
    image: mysql:8
    ports:
      - "3316:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_DATABASE: exchange
      MYSQL_USER: hasnat
      MYSQL_PASSWORD: hasnat123
    volumes:
      - mysqlexchangedata:/var/lib/mysql

  redis:
    image: redis:5
    volumes:
      - redisexchangedata:/data
    ports:
      - "6389:6379"

volumes:
  mysqlexchangedata:
  redisexchangedata:
